development:
 adapter: postgresql
 database: lunchorder_development
 host: localhost

test:
 adapter: postgresql
 database: lunchorder_test
 host: localhost

production:
 encoding: utf8
 pool: 15
 adapter: postgresql
 database: <%= ENV['DATABASE_NAME'] %>
 username: <%= ENV['DATABASE_USERNAME'] %>
 password: <%= ENV['DATABASE_PASSWORD'] %>
